# Generated by Django 3.1 on 2022-03-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'catalog_brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('manufacturer_url', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('lenght', models.IntegerField(blank=True, null=True)),
                ('hight', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('description_main', models.TextField(blank=True, null=True)),
                ('description_specs', models.TextField(blank=True, null=True)),
                ('description_package', models.TextField(blank=True, null=True)),
                ('description_features', models.TextField(blank=True, null=True)),
                ('description_simplified', models.TextField(blank=True, null=True)),
                ('time_update', models.DateTimeField(blank=True, null=True)),
                ('bp1', models.TextField(blank=True, null=True)),
                ('bp2', models.TextField(blank=True, null=True)),
                ('bp3', models.TextField(blank=True, null=True)),
                ('bp4', models.TextField(blank=True, null=True)),
                ('bp5', models.TextField(blank=True, null=True)),
                ('bp6', models.TextField(blank=True, null=True)),
                ('bp7', models.TextField(blank=True, null=True)),
                ('bp8', models.TextField(blank=True, null=True)),
                ('bp9', models.TextField(blank=True, null=True)),
                ('bp10', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parser.brand')),
            ],
            options={
                'verbose_name': 'Новый Продукт',
                'verbose_name_plural': 'Новые Продукты',
                'db_table': 'catalog_product',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.CharField(blank=True, max_length=100, null=True)),
                ('is_main', models.BooleanField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parser.product')),
            ],
            options={
                'db_table': 'catalog_image',
            },
        ),
    ]
